# Catppuccin Mocha — dark theme
[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
bright_foreground = "#cdd6f4"
dim_foreground = "#cdd6f4"

[colors.cursor]
cursor = "#f5e0dc"
text = "#1e1e2e"

[colors.selection]
background = "#f5e0dc"
text = "#1e1e2e"

[colors.vi_mode_cursor]
cursor = "#b4befe"
text = "#1e1e2e"

[colors.search.matches]
background = "#a6adc8"
foreground = "#1e1e2e"

[colors.search.focused_match]
background = "#a6e3a1"
foreground = "#1e1e2e"

[colors.hints.start]
background = "#f9e2af"
foreground = "#1e1e2e"

[colors.hints.end]
background = "#a6adc8"
foreground = "#1e1e2e"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[colors.dim]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[[colors.indexed_colors]]
color = "#fab387"
index = 16

[[colors.indexed_colors]]
color = "#f5e0dc"
index = 17
